# Generated by Django 6.0 on 2025-12-20 12:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock keeping unit identifier', max_length=50, unique=True)),
                ('credits', models.IntegerField(help_text='Number of credits in this pack')),
                ('price_cents', models.IntegerField(help_text='Price in cents ()')),
                ('active', models.BooleanField(default=True, help_text='Whether this pack is currently available for purchase')),
            ],
            options={
                'db_table': 'credit_packs',
                'ordering': ['credits'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('oauth_provider', models.CharField(blank=True, help_text='OAuth provider: google, apple, microsoft or facebook.', max_length=20)),
                ('oauth_id', models.CharField(blank=True, help_text='OAuth id: google id, apple id, microsoft id or facebook id.', max_length=255, null=True, unique=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Number of credits available for unlocking image restorations.', max_digits=10)),
                ('free_preview_used', models.BooleanField(default=False, help_text='Whether the user has used their one free preview.')),
                ('social_share_unlock_used', models.BooleanField(default=False, help_text='Whether the user has used their one-time social media share unlock.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(help_text='Unique credential ID from WebAuthn', max_length=255, unique=True)),
                ('public_key', models.TextField(help_text='Public key credential data')),
                ('sign_count', models.IntegerField(default=0, help_text='Signature counter for replay attack prevention')),
                ('name', models.CharField(help_text='User-friendly device name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passkeys',
            },
        ),
        migrations.CreateModel(
            name='RestorationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_url', models.URLField(help_text='Cloudinary URL of original uploaded image')),
                ('restored_preview_url', models.URLField(blank=True, help_text='Cloudinary URL of watermarked preview', null=True)),
                ('restored_full_url', models.URLField(blank=True, help_text='Cloudinary URL of full-resolution restored image', null=True)),
                ('kie_task_id', models.CharField(blank=True, help_text='Task ID from kie.ai API', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('unlock_method', models.CharField(blank=True, choices=[('paid', 'Paid'), ('social_share', 'Social Share')], help_text='How the image was unlocked', max_length=20, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='When the full image was unlocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this job should be deleted (60 days from creation)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restoration_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for purchase/refund, negative for usage')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('unlock', 'Unlock'), ('refund', 'Refund')], max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe payment intent ID for purchases', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('restoration_job', models.ForeignKey(blank=True, help_text='Associated restoration job for unlocks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviv.restorationjob')),
            ],
            options={
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['oauth_provider', 'oauth_id'], name='users_oauth_p_c54165_idx'),
        ),
        migrations.AddIndex(
            model_name='passkey',
            index=models.Index(fields=['user', 'created_at'], name='passkeys_user_id_77bbda_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationjob',
            index=models.Index(fields=['user', '-created_at'], name='restoration_user_id_6e1be0_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationjob',
            index=models.Index(fields=['status', 'created_at'], name='restoration_status_715342_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationjob',
            index=models.Index(fields=['expires_at'], name='restoration_expires_f48ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='credit_tran_user_id_c82af7_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['stripe_payment_id'], name='credit_tran_stripe__7fa181_idx'),
        ),
    ]
