# Generated by Django 6.0 on 2025-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpack',
            name='price_cents',
            field=models.IntegerField(help_text='Price in cents (EUR)'),
        ),
    ]
