from django.urls import path, include

from reviv.views import api_root, auth, email_passkey, health, passkey, payment, restoration

urlpatterns = [
    path("", api_root, name="api_root"),
    path("auth/oauth/initiate/", auth.oauth_initiate, name="oauth_initiate"),
    path("auth/oauth/callback/<str:provider>/", auth.oauth_callback, name="oauth_callback"),
    path("auth/me/", auth.auth_me, name="auth_me"),
    path("auth/logout/", auth.auth_logout, name="auth_logout"),
    path("auth/oauth/exchange/", auth.oauth_exchange, name="oauth_exchange"),
    path("auth/token/refresh/", auth.token_refresh, name="token_refresh"),
    path("auth/email-passkey/register/begin/",
         email_passkey.email_passkey_register_begin,
         name="email_passkey_register_begin"),
    path("auth/email-passkey/register/complete/",
         email_passkey.email_passkey_register_complete,
         name="email_passkey_register_complete"),
    path("auth/passkey/register/begin/",
         passkey.passkey_register_begin,
         name="passkey_register_begin"),
    path("auth/passkey/register/complete/",
         passkey.passkey_register_complete,
         name="passkey_register_complete"),
    path("auth/passkey/login/begin/",
         passkey.passkey_login_begin,
         name="passkey_login_begin"),
    path("auth/passkey/login/complete/",
         passkey.passkey_login_complete,
         name="passkey_login_complete"),
    path("health/", health.health_check, name="health_check"),
    path("restorations/upload/", restoration.upload_image, name="upload_image"),
    path("restorations/<int:job_id>/status/",
         restoration.restoration_status,
         name="restoration_status"),
    path("restorations/history/", restoration.restoration_history, name="restoration_history"),
    path("restorations/<int:job_id>/",
         restoration.delete_restoration,
         name="delete_restoration"),
    path("restorations/<int:job_id>/unlock/",
         restoration.unlock_restoration,
         name="unlock_restoration"),
    path("restorations/<int:job_id>/share-unlock/",
         restoration.share_unlock,
         name="share_unlock"),
    path("restorations/<int:job_id>/share-redirect/<str:platform>/",
         restoration.share_redirect,
         name="share_redirect"),
    path("restorations/<int:job_id>/confirm-share/",
         restoration.confirm_share,
         name="confirm_share"),
    path("credits/packs/", payment.list_credit_packs, name="credit_packs"),
    path("credits/transactions/", payment.list_transactions, name="credit_transactions"),
    path("credits/purchase/", payment.create_checkout_session, name="credit_purchase"),
    path("credits/webhook/", payment.stripe_webhook, name="credit_webhook"),
]
